### Add a New Post
POST http://localhost:3000/post
Content-Type: application/json

{
  "title": "My First Post",
  "content": "This is the content of my first post.",
  "sender_id": "12345"
}

### Get All Posts
GET http://localhost:3000/post/data

### Get a Post by ID
GET http://localhost:3000/post/<post_id>

### Get Posts by Sender
GET http://localhost:3000/post?sender=<sender_id>

### Update a Post
PUT http://localhost:3000/post/<post_id>
Content-Type: application/json

### Get All Comments
GET http://localhost:3000/comments/data

### Get Comment By Id
GET http://localhost:3000/comments/<comment_id>

### Get comments by post_id
GET http://localhost:3000/comments?post_id=<post_id>


### Create a comment
POST http://localhost:3000/comments
Content-Type: application/json
{
"message": "Hello", "sender_id": "123456", "post_id": "223344"
}

### Update a comment
PUT http://localhost:3000/comments/<comment_id>
Content-Type: application/json

### Get All Users
GET http://localhost:3000/user/data

### Get User By Id
GET http://localhost:3000/user/<user_id>

### Create a User
POST http://localhost:3000/user
Content-Type: application/json
{
"password": "romhagever696969", "email": "rom12345@gmail.com", "username": "romrom123"
}
### Update a User
PUT http://localhost:3000/user/<user_id>
Content-Type: application/json

### Delete a User
DELETE http://localhost:3000/user/<user_id>
Content-Type: application/json

